---
# tasks file for apache-wp-php
- name: Check OS family
  ansible.builtin.debug:
    msg: "OS Family is {{ os_family }}"

- name: Install Apache
  ansible.builtin.package:
    name: "httpd"
    state: present
  when: os_family == 'RedHat'

- name: Install Apache
  ansible.builtin.package:
    name: "apache2"
    state: present
  when: os_family == 'Debian'

- name: Install PHP
  ansible.builtin.package:
    name: "php"
    state: present

- name: Copy website content
  ansible.builtin.copy:
    src: "{{ website_source_dir }}"
    dest: "{{ website_dest_dir }}"
    owner: root
    group: root
    mode: '0755'
  notify:
    - restart apache


